I1 = imread('ABL_4piH.png');
imshow(I1);
hold on;
%I2 = imread('ABL_4piH.png');

hxlabel = xlabel('$${x}_{H} $$', 'Interpreter', 'Latex');
hylabel = ylabel('$${z}_{H} $$', 'Interpreter', 'Latex');

%================ Axis properties =====================%
% set( gca                       , ...
%     'FontName'   , 'Times' );

set([ hxlabel, hylabel], ...
    'FontName'   , 'Times', 'fontweight','normal');
% set(gca                      , ...
%     'FontSize'   , 50             );
set([hxlabel, hylabel]  , ...
    'FontSize'   , 30          );
  set(hylabel,'pos',[-20 35],'rot',360);
%  set(hx1label,'pos',[.75 .52]);
% 
%  set([hlegend]  , ...
%      'FontSize'   , 30          );

% a = gca;
% set(a, ...
%   'Box'         , 'off'     , ...
%   'TickDir'     , ''     , ...
%   'TickLength'  , [.0125 .0125] , ...
%   'XMinorTick'  , 'off'      , ...
%   'YMinorTick'  , 'off'      , ...
%   'YGrid'       , 'off'      , ...
%   'XColor'      , [0 0 0], ...
%   'YColor'      , [0 0 0], ...
%   'LineWidth'   , 2.5         );
% 

set(gcf, 'PaperUnits', 'inches');
set(gcf, 'PaperSize', [18 14.5]);
set(gcf, 'PaperPositionMode', 'manual');
set(gcf, 'PaperPosition', [0 0 18 14.5]);


filename = strcat('ABL_2.png');
print(gcf, '-dpng', filename);